travis:
  secure:
    BINSTAR_TOKEN: bbGvIS5DC+owkBTTcJS5k8K5IOjWfX9WxTAoZIV86Utyt5PusgVqhivumOwDovQEGP39InJJxc1oq0zBz7G3V+T6LLQwTmMaYxSd9SnpCRfx0VSm2uMwGYtx+3anw5gaZjFUxxKIC8fsD/70TbDyRLUesdyugYHgMf72Y6pLSyHL4uweTmt+CEwVCRVdK8vXGc14jVS5tSRmIc5olDkmfzW4rYf/Sd/5RNexnLsmH8RqgAdkywsxUMLZjNFhHV9JaqOA1xG1DMSWAD6EvOTXtTxNDUkNdqAXmDVP6KtCgcS6cInIPu1ccBuIRfPy7XCF4ow1uUuLybWG5wdQ5jfLfa8jMugYMII3SQ+9gKocCVcIHXRQDV8KYp+XQ9WlydLpMjxDgkpmK1kBymcGZFphL/f2EUrK2seCYkJGad+H7iG5Od3KmTH5ieI9RFpvfPYkPfvsh205Ji3LWWyNWJdvQ+uEedcpaWpODZRi0ZRmpuiV/76PZsrgVp+XZuUEtcxNdVoyMiVkJf4ilzuQ1ByYGOcq1Svo+5JacSfLEiYgnAIDD5hjjjmtSX3nabAyA00/hp8w7FHdCaoimp79gYmwnUq1/UhuGZePezHNeVJSs7gMlQgZxRB3mw6KFqBNaQQicWpojN4NHRHruEBnOUT5ORTEUxWookgvonnTQdUeusg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
