travis:
  secure:
    BINSTAR_TOKEN: V8oL24b4F/meKSio5D3Slmuu+Q0iudW2vakgAziJU6OVjNR/l4NJBYD1dcEpCgiyTFMbiuTEY6nPYvtBIYnIP+pVrwuKL4pqs0bMSB3j6Hzy2rO9VS8S3k7vgx/ANjzrHSPmN6hB2TT7GhCPxTt0TZ30wAH5+sHNDWMxl8Ya2c+tw/XUHrs/IEMkUHf3Q+iqy+baoCTRC5zIUphoGD6MjUg4H0uokunn/iGUsmobVS5T26M/ifkLTE0ATKfZNmsYO6llmpq7MEZYWJ7dpuEs6InbqQW63qMRSYTy+dmcjGhXXH3gW1GiN0DoS65OC8e3mB0bIDGQJS0ZyflDW4E3BFfTGFgtUYcVJ69XEUTVeQAxcxiEi1cyi65dYHt9f7kvChdyBtsXDGevNThYVLFpmDkjp/pl3XBXwGPM7U0WVUMsL5TwC+PtMWyntHKlYInnlG3ProbRV3iOxCvonfBJSGobavUcdDfNKng4aOlcUnMxjPqgKSJZZXQJBcUa9RqTsM2x5Dbd87VSSkY2MqkvfWpCeWXYd3qCq6UQh3bAckefa7eaRNGhUNnKWD27Xmdj5KtCVMuZHJVkbGskOFtO/MjD1Ug2w06ETrzJhI5g/dkEzO57NqFA7LQY0jW2nw8GceL1CtJwTdcvUJIOHIjoxlWQds739UiFQii/5NfoOOk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
